import { PrismaClient, Role, CalendarEventType, Priority, TaskStatus, SalesWorkflowStage, DepartmentStatus, QCResult } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding Manufacturing ERP Database (Super Admin & System Default Data)...');

  // Clean existing tables in safe sequence
  await prisma.calendarEvent.deleteMany();
  await prisma.stageLog.deleteMany();
  await prisma.note.deleteMany();
  await prisma.drawing.deleteMany();
  await prisma.task.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.client.deleteMany();
  await prisma.user.deleteMany();

  // Create Default Hashed Password
  const hashedPassword = await bcrypt.hash('Admin@123', 10);

  // 1. Create Initial Super Admin Account
  const superAdmin = await prisma.user.create({
    data: {
      name: 'Super Admin',
      username: 'superadmin',
      email: 'admin@flangeerp.com',
      password: hashedPassword,
      role: Role.SUPER_ADMIN,
      isActive: true,
    },
  });

  console.log('✅ Super Admin Account Created: admin@flangeerp.com (Password: Admin@123)');

  // 2. Create Sample Clients (Generated by Sales)
  const client1 = await prisma.client.create({
    data: {
      clientCode: 'CL-1001',
      companyName: 'Apex Heavy Engineering Pvt Ltd',
      contactName: 'Rajesh Mehta',
      contactNo: '+91 98765 43210',
      email: 'contact@apexheavy.com',
      address: 'Plot 42, Industrial Area Phase II, Pune',
      gstNumber: '27AAACA12341Z5',
      createdById: superAdmin.id,
    },
  });

  const client2 = await prisma.client.create({
    data: {
      clientCode: 'CL-1002',
      companyName: 'Bharat Forgings & Piping Co.',
      contactName: 'Vikram Singh',
      contactNo: '+91 91234 56789',
      email: 'vikram@bharatforgings.com',
      address: 'GIDC Estate, Sector 5, Vadodara',
      gstNumber: '24AAACB98761Z2',
      createdById: superAdmin.id,
    },
  });

  console.log('✅ Sample Clients Created with Client Codes: CL-1001, CL-1002');

  // 3. Create Sample Orders with Custom Pipelines
  const order1 = await prisma.order.create({
    data: {
      orderNumber: 'ORD-2026-001',
      poNumber: 'PO-APEX-9981',
      clientId: client1.id,
      clientCode: client1.clientCode,
      technicalRequirements: 'High Pressure Stainless Steel Flanges SS316L, 600# Rating, Serrated Finish.',
      materialRequirements: 'SS316L Round Bars Dia 250mm',
      requiredQuantity: 50,
      status: DepartmentStatus.IN_PROGRESS,
      drawingApproved: true,
      createdById: superAdmin.id,

      // Pipeline Customizer Options
      purchaseRequired: true,
      productionRequired: true,
      qualityTestingRequired: true,
      dispatchRequired: true,

      salesWorkflowStage: SalesWorkflowStage.ORDER_CONFIRMED,
      purchaseStatus: DepartmentStatus.COMPLETED,
      vendorSelected: 'Jindal Stainless Steel Works',
      procurementNotes: 'Raw material received and verified in warehouse stock.',

      productionStatus: DepartmentStatus.IN_PROGRESS,
      shopFloorNotes: 'Machining stage 60% completed on CNC lathe #4.',

      qualityStatus: DepartmentStatus.PENDING,
      qcResult: QCResult.PENDING,

      dispatchStatus: DepartmentStatus.PENDING,
      salesVerification: DepartmentStatus.PENDING,

      items: {
        create: [
          {
            itemName: 'SS316L Weld Neck Flange',
            size: '6 inch 600# RF',
            quantity: 50,
            unitPrice: 4500.00,
          },
        ],
      },
      stageLogs: {
        create: [
          {
            department: 'SALES',
            action: 'Order Confirmed',
            currentStatus: 'ORDER_CONFIRMED',
            remarks: 'Drawing and PO verified with client specification.',
            changedById: superAdmin.id,
          },
          {
            department: 'PURCHASE',
            action: 'Purchase Done',
            currentStatus: 'COMPLETED',
            remarks: 'Material procured from Jindal Stainless Steel Works.',
            changedById: superAdmin.id,
          },
        ],
      },
    },
  });

  const order2 = await prisma.order.create({
    data: {
      orderNumber: 'ORD-2026-002',
      poNumber: 'PO-BFP-5542',
      clientId: client2.id,
      clientCode: client2.clientCode,
      technicalRequirements: 'Carbon Steel Blind Flanges A105, 300# Rating, Zinc Plated.',
      materialRequirements: 'A105 Forged Blanks',
      requiredQuantity: 100,
      status: DepartmentStatus.IN_PROGRESS,
      drawingApproved: true,
      createdById: superAdmin.id,

      // Pipeline Customizer (No Quality Testing Required demo)
      purchaseRequired: true,
      productionRequired: true,
      qualityTestingRequired: false,
      dispatchRequired: true,

      salesWorkflowStage: SalesWorkflowStage.ORDER_CONFIRMED,
      purchaseStatus: DepartmentStatus.COMPLETED,
      vendorSelected: 'Global Steel Supply Inc.',

      productionStatus: DepartmentStatus.COMPLETED,
      shopFloorNotes: 'All 100 flanges forged and machined. Ready for dispatch.',

      qualityStatus: DepartmentStatus.COMPLETED,
      qcResult: QCResult.PASSED,

      dispatchStatus: DepartmentStatus.PENDING,
      salesVerification: DepartmentStatus.PENDING,

      items: {
        create: [
          {
            itemName: 'A105 Blind Flange',
            size: '4 inch 300#',
            quantity: 100,
            unitPrice: 2200.00,
          },
        ],
      },
    },
  });

  console.log('✅ Sample Orders Created: ORD-2026-001, ORD-2026-002');

  // 4. Create Sample Tasks (Cross-Team Assignment)
  await prisma.task.create({
    data: {
      orderId: order1.id,
      title: 'Inspect Raw Material SS316L Certification',
      description: 'Check mill test certificate (MTC) from Jindal Stainless.',
      priority: Priority.HIGH,
      status: TaskStatus.IN_PROGRESS,
      assignedToDepartment: Role.QUALITY_TESTING,
      createdById: superAdmin.id,
      dueDate: new Date(Date.now() + 86400000 * 2), // +2 days
    },
  });

  await prisma.task.create({
    data: {
      title: 'Monthly Safety Audit & Calibration',
      description: 'Perform shop floor equipment safety checks across all CNC units.',
      priority: Priority.MEDIUM,
      status: TaskStatus.PENDING,
      assignedToDepartment: Role.PRODUCTION,
      createdById: superAdmin.id,
      dueDate: new Date(Date.now() + 86400000 * 5),
    },
  });

  console.log('✅ Sample Tasks Created');

  // 5. Create Sample Calendar Events
  await prisma.calendarEvent.create({
    data: {
      title: 'Client Technical Inspection Meeting - ORD-2026-001',
      type: CalendarEventType.MEETING,
      eventDate: new Date(),
      description: 'Review dimensional drawings and third-party inspection schedule with client representative.',
      createdById: superAdmin.id,
    },
  });

  await prisma.calendarEvent.create({
    data: {
      title: 'Material Delivery Deadline - PO-APEX-9981',
      type: CalendarEventType.DEADLINE,
      eventDate: new Date(Date.now() + 86400000 * 3),
      description: 'Expected arrival of SS316L forged billets.',
      createdById: superAdmin.id,
    },
  });

  await prisma.calendarEvent.create({
    data: {
      title: 'Plant Founders Day Milestone',
      type: CalendarEventType.MILESTONE,
      eventDate: new Date(Date.now() + 86400000 * 7),
      description: 'Annual manufacturing plant performance review and awards.',
      createdById: superAdmin.id,
    },
  });

  console.log('✅ Sample Calendar Events Created');
  console.log('🎉 Seeding Complete!');
}

main()
  .catch((e) => {
    console.error('❌ Seeding Failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });